read_hdl -vhdl {A_input_register.vhd}
read_hdl -vhdl {adder_hold_register.vhd}
read_hdl -vhdl {alu.vhd}
read_hdl -vhdl {alu_logic.vhd}
read_hdl -vhdl {B_input_register.vhd}
read_hdl -vhdl {8_bit_adder.vhd}
read_hdl -vhdl {8_bit_and.vhd}
read_hdl -vhdl {8_bit_or.vhd}
read_hdl -vhdl {8_bit_shift.vhd}
read_hdl -vhdl {8_bit_xor.vhd}
read_hdl -vhdl {register_8bit.vhd}
read_hdl -vhdl {register_8bit_behaviour_cfg.vhd}
read_hdl -vhdl {eight_bit_shift_behaviour_cfg.vhd}
read_hdl -vhdl {eight_bit_and_behavioural_cfg.vhd}
read_hdl -vhdl {eight_bit_xor_behavioural_cfg.vhd}
read_hdl -vhdl {eight_bit_or_behavioural_cfg.vhd}
read_hdl -vhdl {eight_bit_adder_behaviour_cfg.vhd}
read_hdl -vhdl {adder_hold_register_arch_cfg.vhd}
read_hdl -vhdl {a_input_register_strucutural_cfg.vhd}
read_hdl -vhdl {b_input_register_structural_cfg.vhd}
read_hdl -vhdl {alu_logic_structural_cfg.vhd}
read_hdl -vhdl {alu_structural_cfg.vhd}
